language: node_js
node_js:
- "11.15.0"
os: osx
sudo: false

git:
  submodules: true

cache:
  directories:
  - node_modules

compiler:
  - clang
  - gcc

script:
- npm i
- ./build-txcircuits.sh
- npm run extension:build
